language: node_js
node_js:
  - "7"

matrix:
  fast_finish: true
  include:
    - os: linux
      node_js: "7"
      env: TEST_SUITE=test
    - os: linux
      node_js: "7"
      env: TEST_SUITE=lint

script: ./npm run $TEST_SUITE

